{% set version = "5.3.0" %}

package:
  name: auditwheel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/auditwheel/auditwheel-{{ version }}.tar.gz
  sha256: d0be87b5b6fb767eacf1ea4afa3292574cb0f4473a3c0ba55bc9dff1d0b5a333

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pyelftools >=0.24
    - __linux

test:
  commands:
    - auditwheel -h

about:
  home: https://github.com/pypa/auditwheel
  license: MIT
  license_file: LICENSE
  summary: Linux wheel verification tool to ensure compatibility

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
