{% set name = "auditwheel" %}
{% set version = "6.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 277f3b315ad0b04df0a2be2d126c3fd39930bc265df0f9589d78c970ff06f52b

build:
  number: 0
  skip: true # [py<310 or win or osx]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - auditwheel = auditwheel.main:main

requirements:
  host:
    - python
    - pip
    - setuptools >=61
    - setuptools-scm >=8
  run:
    - python
    - packaging >=20.9
    - pyelftools >=0.24

test:
  imports:
    - auditwheel
  source_files:
    - tests/
  requires:
    - pip
    - python
    - pytest >=3.4
    - docker-py
    - pretend
  commands:
    - pip check
    - auditwheel --help
    - pytest -v tests/

about:
  home: https://github.com/pypa/auditwheel
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - src/auditwheel/_vendor/wheel/LICENSE.txt
  summary: Auditing and relabeling cross-distribution Linux wheels.
  description: |
    Auditing and relabeling of PEP 600 manylinux_x_y, PEP 513 manylinux1,
    PEP 571 manylinux2010 and PEP 599 manylinux2014 Linux wheels.
  doc_url: https://github.com/pypa/auditwheel
  dev_url: https://github.com/pypa/auditwheel

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - BastianZim
