travis:
  secure:
    BINSTAR_TOKEN: hn5Oev/0425ZJfgqQyL0sd4I+uFfMBGsLiI5ayonLB72v4NSOvL3wQRWt33W9wG7i+4CC0FZxxpmbvrPrkvtQ1VTZdggvg+5kuqddO6PpFEll6sxOB/wV7P5o9VX3B/Unkmb4qU+gwBDTUiYkYbKuwAAErfLUh/Yp9Hr/F1TfS/lmXIAFnCokneuUfrbtD429uXgqYTzfJUC/gDs60UY4dzgitj2HW8w3ag3wTpcyNHOdT44fFkmKTFs8OG9RtwiEuWrG/KXe966v18wHzBV6qj1qIZ8rQB0L7PruhBqsqcLqfzh5Gx3Xv5m2wWkG1d1el3Hq0XovvjrXodiglJkboXUofs4+Yx90XQhNve4RV5aPqUbt3PICJtIBnhcjhSPkvqo8xXTUkEqFCUCMwNGTodvU4dr6RLfrB/zPE5mMO6GjSUy2gAX4JN0+isYRwjJ1QFSxXZgo7kG5Z97ldo4jIlGKR8Y1RZKkZ+8m3xab3FDXWifVxaIV1mzkCkCCw2jg9DbFCRepWehftTKJbbWRD7Mt+w5KcWsSS6DO/FrSLaYuNRqD7gechokFORWzytmHyJ8JXQ41wNHHh2rvxweSFiuAEUMBw/2DUROdq7DL4LM9pNB/zUU0GCNCCNvOSpYLjiGR6/G9E6GC0SApuw771P/tTKf7JIS9MmbwvK+ebM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
