travis:
  secure:
    BINSTAR_TOKEN: UPMcUVrtYjubl6mLOxgFEAbCEBTNLnovY9wbfCog7r3L5zcocR0U6vrsCtEsz6cjDsz4EPmHwwtWkYPofSVN82Q2XHIvRbGyjuzcPvHXXLbZu1e6qm9L6KxBMQbhzDCm9IuLY5rai/TUGJt1DKtajawkI0RGt67PftMuJnVGh6/nuzmpCTrmLGvByswmjLOCTVMxGwUjito7qEESoREglDCL8H4XxW4moG01bPUuuygXkE4pdAP58KkrVX54fixkVDX3txhxAUx7bkOV3Dn4WQoqLZUVT7AVwIPqELjKiBezyUJNOV9UnfSiw4ENbZG/61MANVpcuqffQu5QvPB19GePpdBXcgy/HZEOJ7iqBdoOTv4b99V13HS3qKzmKYgFdXmBIJV/v2TZm1jDZL2nLMXzCJk/H1IaToh+iqlUP2WHRrpcCc3t4nfhDe/zXVYzWvF3oBNidCV1Mf+jzBoI/VwkO8RuKayleou1/BpIJs2wv3SBJ3eB8di0kNSxg6S0eFIhdEQekqAfXbR/+xOVTaBDkmOWtGRpKFBe+XCrQOs3VpA/PDagD6HufpXPkqZ9fLhptrVq2F0Z3qGkvyi+iiwF3KaPh8Vzshwn1EqwvzCpBBP079eDV7z6PJDq0AGAuPS2Z4PtXZOsA2P2xMEv0jKC8eZuxF8S/Hs+Djcy8fY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
